<a href="https://colab.research.google.com/github/MaheenZaheer/Machine-Learning/blob/main/ClassificationAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = sns.load_dataset("titanic")

In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

EDA

In [6]:
df.drop(["who","adult_male","deck","alive"], axis =1, inplace = True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   embark_town  889 non-null    object
 10  alone        891 non-null    bool
dtypes: bool(1), category(1), float64(2), int64(4), object(3)
memory usage: 64.6+ KB

In [8]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
embark_town      2
alone            0
dtype: int64

In [9]:
df.dropna(subset = "embarked", inplace = True)

In [10]:
df["age"].fillna(df["age"].mean(),inplace = True )

/tmp/ipykernel_698/4236963216.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(),inplace = True )

In [11]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
embark_town    0
alone          0
dtype: int64

Feature Engineering

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     889 non-null    int64
 1   pclass       889 non-null    int64
 2   sex          889 non-null    object
 3   age          889 non-null    float64
 4   sibsp        889 non-null    int64
 5   parch        889 non-null    int64
 6   fare         889 non-null    float64
 7   embarked     889 non-null    object
 8   class        889 non-null    category
 9   embark_town  889 non-null    object
 10  alone        889 non-null    bool
dtypes: bool(1), category(1), float64(2), int64(4), object(3)
memory usage: 71.3+ KB

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
encoder1 = LabelEncoder()
df = pd.get_dummies(df, dtype=int)

In [15]:
df["alone"] = df["alone"].astype(int)
df

,survived,pclass,age,sibsp,parch,fare,alone,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,class_First,class_Second,class_Third,embark_town_Cherbourg,embark_town_Queenstown,embark_town_Southampton
0,0,3,22.000000,1,0,7.2500,0,0,1,0,0,1,0,0,1,0,0,1
1,1,1,38.000000,1,0,71.2833,0,1,0,1,0,0,1,0,0,1,0,0
2,1,3,26.000000,0,0,7.9250,1,1,0,0,0,1,0,0,1,0,0,1
3,1,1,35.000000,1,0,53.1000,0,1,0,0,0,1,1,0,0,0,0,1
4,0,3,35.000000,0,0,8.0500,1,0,1,0,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.000000,0,0,13.0000,1,0,1,0,0,1,0,1,0,0,0,1
887,1,1,19.000000,0,0,30.0000,1,1,0,0,0,1,1,0,0,0,0,1
888,0,3,29.642093,1,2,23.4500,0,1,0,0,0,1,0,0,1,0,0,1
889,1,1,26.000000,0,0,30.0000,1,0,1,1,0,0,1,0,0,1,0,0
890,0,3,32.000000,0,0,7.7500,1,0,1,0,1,0,0,0,1,0,1,0

Logistic Regression

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix

In [17]:
X = df.drop("survived", axis = 1)
y = df["survived"]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

In [19]:
model = LogisticRegression()
model.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [20]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1])

In [21]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

In [22]:
accuracy

0.8033707865168539

In [23]:
precision

0.7391304347826086

In [24]:
recall

0.75

In [25]:
f1_score

In [26]:
from sklearn.metrics import classification_report

In [27]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.84      0.84      0.84       110
           1       0.74      0.75      0.74        68

    accuracy                           0.80       178
   macro avg       0.79      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178

In [28]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[92, 18],
       [17, 51]])

KNN (K Neighriest Neighboor)

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
model2 = KNeighborsClassifier(n_neighbors=3)

In [33]:
model2.fit(X_train_scaled,y_train)

KNeighborsClassifier(n_neighbors=3)

In [34]:
y_pred2 = model2.predict(X_test_scaled)
y_pred2

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1])

In [35]:
accuracy2 = accuracy_score(y_test, y_pred2)
precision2 = precision_score(y_test, y_pred2)
recall2 = recall_score(y_test, y_pred2)
f1_score2 = f1_score(y_test, y_pred2)

In [36]:
accuracy2

0.7696629213483146

In [37]:
report2 = classification_report(y_test, y_pred2)
print(report2)

              precision    recall  f1-score   support

           0       0.81      0.83      0.82       110
           1       0.71      0.68      0.69        68

    accuracy                           0.77       178
   macro avg       0.76      0.75      0.75       178
weighted avg       0.77      0.77      0.77       178

**Navie** **Bayes**

unscaled

In [38]:
from sklearn.naive_bayes import GaussianNB

In [39]:
model3 = GaussianNB()

In [40]:
model3.fit(X_train,y_train)

GaussianNB()

In [41]:
y_pred3 = model3.predict(X_test)

In [42]:
accuracy3 = accuracy_score(y_test, y_pred3)
precision3 = precision_score(y_test, y_pred3)
recall3 = recall_score(y_test, y_pred3)
f1_score3 = f1_score(y_test, y_pred3)

In [43]:
accuracy3

0.7696629213483146

In [44]:
report3 = classification_report(y_test, y_pred3)
print(report3)

              precision    recall  f1-score   support

           0       0.84      0.77      0.81       110
           1       0.68      0.76      0.72        68

    accuracy                           0.77       178
   macro avg       0.76      0.77      0.76       178
weighted avg       0.78      0.77      0.77       178

scaled

In [45]:
model4 = GaussianNB()

In [46]:
model4.fit(X_train_scaled,y_train)

GaussianNB()

In [47]:
y_pred4 = model4.predict(X_test_scaled)

In [48]:
accuracy4 = accuracy_score(y_test, y_pred4)
accuracy4

0.7696629213483146

In [49]:
report4 = classification_report(y_test, y_pred4)
print(report4)

              precision    recall  f1-score   support

           0       0.84      0.77      0.81       110
           1       0.68      0.76      0.72        68

    accuracy                           0.77       178
   macro avg       0.76      0.77      0.76       178
weighted avg       0.78      0.77      0.77       178

Decision Trees

In [50]:
from sklearn import tree

In [51]:
model6 = tree.DecisionTreeClassifier()

In [52]:
model6.fit(X_train_scaled,y_train)

DecisionTreeClassifier()

In [53]:
y_pred6 = model6.predict(X_test_scaled)

In [54]:
accuracy6 = accuracy_score(y_test, y_pred6)
accuracy6

0.8258426966292135

In [55]:
report6 = classification_report(y_test, y_pred6)
print(report6)

              precision    recall  f1-score   support

           0       0.88      0.84      0.86       110
           1       0.75      0.81      0.78        68

    accuracy                           0.83       178
   macro avg       0.81      0.82      0.82       178
weighted avg       0.83      0.83      0.83       178

SVM

In [56]:
from sklearn import svm

In [57]:
model7 = svm.SVC()

In [58]:
model7.fit(X_train_scaled,y_train)

SVC()

In [59]:
y_pred7 = model7.predict(X_test_scaled)

In [60]:
accuracy7 = accuracy_score(y_test, y_pred7)
accuracy7

0.8089887640449438

In [61]:
report7 = classification_report(y_test, y_pred7)
print(report7)

              precision    recall  f1-score   support

           0       0.82      0.89      0.85       110
           1       0.79      0.68      0.73        68

    accuracy                           0.81       178
   macro avg       0.80      0.78      0.79       178
weighted avg       0.81      0.81      0.81       178

Cross validation

In [1]:
from sklearn.model_selection import cross_val_score

In [64]:
model = svm.SVC()
score = cross_val_score(model, X_train_scaled, y_train, cv=5)
score

array([0.83216783, 0.87323944, 0.83098592, 0.80985915, 0.78169014])

In [67]:
np.mean(score)

np.float64(0.8255884960110313)