<a href="https://colab.research.google.com/github/MaheenZaheer/Machine-Learning/blob/main/Model_Optimization_SVM_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as pyplot

In [42]:
df = sns.load_dataset("iris")

In [43]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [44]:
df.shape

(150, 5)

In [45]:
x = df.drop("species",axis=1)
y = df["species"]

In [46]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [47]:
from sklearn import svm
model_svm = svm.SVC(kernel="linear",C=10)

In [48]:
model_svm.fit(x_train,y_train)

SVC(C=10, kernel='linear')

In [49]:
model_svm.score(x_test,y_test)

0.9666666666666667

Grid Search CV

In [50]:
from sklearn.model_selection import GridSearchCV

In [51]:
cm = GridSearchCV((model_svm),{
    "C":[1,10,20,30],
    "gamma":["auto","scale"]
},cv=5,return_train_score=False)

In [52]:
cm.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(C=10, kernel='linear'),
             param_grid={'C': [1, 10, 20, 30], 'gamma': ['auto', 'scale']})

In [53]:
result = pd.DataFrame(cm.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003891,0.000773,0.002763,0.000560,1,auto,"{'C': 1, 'gamma': 'auto'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002256,0.000087,0.001663,0.000041,1,scale,"{'C': 1, 'gamma': 'scale'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002320,0.000420,0.001697,0.000164,10,auto,"{'C': 10, 'gamma': 'auto'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,3
3,0.002469,0.000395,0.001767,0.000341,10,scale,"{'C': 10, 'gamma': 'scale'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,3
4,0.002120,0.000028,0.001597,0.000023,20,auto,"{'C': 20, 'gamma': 'auto'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,5
5,0.002181,0.000048,0.001597,0.000026,20,scale,"{'C': 20, 'gamma': 'scale'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,5
6,0.002211,0.000112,0.001612,0.000038,30,auto,"{'C': 30, 'gamma': 'auto'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7
7,0.002235,0.000111,0.001645,0.000032,30,scale,"{'C': 30, 'gamma': 'scale'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

KNN

In [54]:
from sklearn.neighbors import KNeighborsClassifier

In [55]:
cm2 = GridSearchCV(KNeighborsClassifier(),{
    "n_neighbors":[3,5,7,9,11,13,15,17,19,21,25,27,31],
    "weights":["uniform","distance"],
    "metric":["euclidean", "manhattan"]
}
)

In [56]:
cm2.fit(x,y)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 25,
                                         27, 31],
                         'weights': ['uniform', 'distance']})

In [57]:
result = pd.DataFrame(cm2.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002548,0.000238,0.004212,0.000881,euclidean,3,uniform,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,27
1,0.002148,0.000120,0.002384,0.000048,euclidean,3,distance,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,27
2,0.002138,0.000033,0.003093,0.000130,euclidean,5,uniform,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,7
3,0.002055,0.000096,0.002358,0.000162,euclidean,5,distance,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,27
4,0.002057,0.000023,0.003249,0.000238,euclidean,7,uniform,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,2
5,0.002133,0.000058,0.002431,0.000086,euclidean,7,distance,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,2
6,0.002078,0.000071,0.003001,0.000062,euclidean,9,uniform,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,7
7,0.002087,0.000104,0.002313,0.000082,euclidean,9,distance,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,7
8,0.001967,0.000023,0.002955,0.000068,euclidean,11,uniform,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.933333,1.000000,1.000000,0.966667,1.0,0.980000,0.026667,2
9,0.001951,0.000022,0.002277,0.000040,euclidean,11,distance,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
10,0.002005,0.000028,0.002967,0.000075,euclidean,13,uniform,"{'metric': 'euclidean', 'n_neighbors': 13, 'we...",0.933333,1.000000,0.966667,0.966667,1.0,0.973333,0.024944,7
11,0.002068,0.000126,0.002379,0.000160,euclidean,13,distance,"{'metric': 'euclidean', 'n_neighbors': 13, 'we...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,2
12,0.002283,0.000256,0.003415,0.000287,euclidean,15,uniform,"{'metric': 'euclidean', 'n_neighbors': 15, 'we...",0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,27
13,0.002194,0.000185,0.002781,0.000825,euclidean,15,distance,"{'metric': 'euclidean', 'n_neighbors': 15, 'we...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,7
14,0.002099,0.000087,0.003121,0.000059,euclidean,17,uniform,"{'metric': 'euclidean', 'n_neighbors': 17, 'we...",0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,27
15,0.002124,0.000055,0.002483,0.000116,euclidean,17,distance,"{'metric': 'euclidean', 'n_neighbors': 17, 'we...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,7
16,0.002101,0.000084,0.003055,0.000029,euclidean,19,uniform,"{'metric': 'euclidean', 'n_neighbors': 19, 'we...",0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,27
17,0.002049,0.000052,0.002408,0.000083,euclidean,19,distance,"{'metric': 'euclidean', 'n_neighbors': 19, 'we...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,7
18,0.002041,0.000040,0.003036,0.000056,euclidean,21,uniform,"{'metric': 'euclidean', 'n_neighbors': 21, 'we...",0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,27
19,0.001990,0.000040,0.002312,0.000021,euclidean,21,distance,"{'metric': 'euclidean', 'n_neighbors': 21, 'we...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,7
20,0.001993,0.000008,0.002985,0.000032,euclidean,25,uniform,"{'metric': 'euclidean', 'n_neighbors': 25, 'we...",0.933333,0.966667,0.933333,0.966667,1.0,0.960000,0.024944,43
21,0.002155,0.000118,0.002760,0.000268,euclidean,25,distance,"{'metric': 'euclidean', 'n_neighbors': 25, 'we...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,27
22,0.002090,0.000101,0.003035,0.000029,euclidean,27,uniform,"{'metric': 'euclidean', 'n_neighbors': 27, 'we...",0.900000,0.966667,0.933333,0.933333,1.0,0.946667,0.033993,50
23,0.002138,0.000093,0.002493,0.000065,euclidean,27,distance,"{'metric': 'euclidean', 'n_neighbors': 27, 'we...",0.966667,0.966667,0.966667,0.966667,1.0,0.973333,0.013333,7
24,0.002112,0.000063,0.003167,0.000110,euclidean,31,uniform,"{'metric': 'euclidean', 'n_neighbors': 31, 'we...",0.900000,0.966667,0.900000,0.900000,1.0,0.933333,0.042164,52
25,0.001980,0.000019,0.002369,0.000074,euclidean,31,distance,"{'metric': 'euclidean', 'n_neighbors': 31, 'we...",0.966667,0.966667,0.966667,0.966667,1.0,0.973333,0.013333,7
26,0.002133,0.000143,0.003055,0.000156,manhattan,3,uniform,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,43
27,0.002031,0.000073,0.002263,0.000025,manhattan,3,distance,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,43
28,0.002036,0.000028,0.002911,0.000027,manhattan,5,uniform,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,39
29,0.003070,0.000486,0.003771,0.001121,manhattan,5,distance,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,39
30,0.002514,0.000655,0.003414,0.000510,manhattan,7,uniform,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,7
31,0.002063,0.000037,0.002372,0.000055,manhattan,7,distance,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,39
32,0.002024,0.000021,0.002930,0.000015,manhattan,9,uniform,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,7
33,0.002025,0.000017,0.002356,0.000101,manhattan,9,distance,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,39
34,0.002068,0.000031,0.003070,0.000079,manhattan,11,uniform,"{'metric': 'manhattan', 'n_neighbors': 11, 'we...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,2
35,0.002107,0.000067,0.002400,0.000152,manhattan,11,distance,"{'metric': 'manhattan', 'n_neighbors': 11, 'we...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,27
36,0.002106,0.000071,0.003019,0.000055,manhattan,13,uniform,"{'metric': 'manhattan', 'n_neighbors': 13, 'we...",0.933333,1.000000,0.966667,0.966667,1.0,0.973333,0.024944,7
37,0.002535,0.000856,0.003314,0.001339,manhattan,13,distance,"{'metric': 'manhattan', 'n_neighbors': 13, 'we...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,27
38,0.002139,0.000043,0.003216,0.000067,manhattan,15,uniform,"{'metric': 'manhattan', 'n_neighbors': 15, 'we...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,7
39,0.002435,0.000352,0.002598,0.000141,manhattan,15,distance,"{'metric': 'manhattan', 'n_neighbors': 15, 'we...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,7
40,0.002272,0.000259,0.003254,0.000243,manhattan,17,uniform,"{'metric': 'manhattan', 'n_neighbors': 17, 'we...",0.933333,1.000000,0.966667,0.933333,1.0,0.966667,0.029814,38
41,0.002117,0.000193,0.002376,0.000033,manhattan,17,distance,"{'metric': 'manhattan', 'n_neighbors': 17, 'we...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,7
42,0.002127,0.000061,0.003143,0.000092,manhattan,19,uniform,"{'metric': 'manhattan', 'n_neighbors': 19, 'we...",0.933333,1.000000,0.966667,0.966667,1.0,0.973333,0.024944,7
43,0.002186,0.000106,0.002659,0.000333,manhattan,19,distance,"{'metric': 'manhattan', 'n_neighbors': 19, 'we...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,7
44,0.002320,0.000412,0.003273,0.000262,manhattan,21,uniform,"{'metric': 'manhattan', 'n_neighbors': 21, 'we...",0.933333,1.000000,0.966667,0.966667,1.0,0.973333,0.024944,7
45,0.002163,0.000081,0.002454,0.000033,manhattan,21,distance,"{'metric': 'manhattan', 'n_neighbors': 21, 'we...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,7
46,0.002100,0.000040,0.003090,0.000030,manhattan,25,uniform,"{'metric': 'manhattan', 'n_neighbors': 25, 'we...",0.933333,0.966667,0.933333,0.966667,1.0,0.960000,0.024944,43
47,0.002085,0.000011,0.002424,0.000018,manhattan,25,distance,"{'metric': 'manhattan', 'n_neighbors': 25, 'we...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,27
48,0.002382,0.000250,0.003684,0.000494,manhattan,27,uniform,"{'metric': 'manhattan', 'n_neighbors': 27, 'we...",0.933333,0.966667,0.933333,0.933333,1.0,0.953333,0.026667,48
49,0.002367,0.000303,0.002600,0.000079,manhattan,27,distance,"{'metric': 'manhattan', 'n_neighbors': 27, 'we...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,43
50,0.002208,0.000024,0.003328,0.000157,manhattan,31,uniform,"{'metric': 'manhattan', 'n_neighbors': 31, 'we...",0.933333,0.966667,0.866667,0.933333,1.0,0.940000,0.044222,51
51,0.002556,0.000283,0.002693,0.000073,manhattan,31,distance,"{'metric': 'manhattan', 'n_neighbors': 31, 'we...",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,48

Randomized Search CV

In [58]:
from sklearn.model_selection import RandomizedSearchCV

In [59]:
cm3 = RandomizedSearchCV(KNeighborsClassifier(),{
    "n_neighbors":[3,5,7,9,11,13,15,17,19,21,25,27,31],
    "weights":["uniform","distance"],
    "metric":["euclidean", "manhattan"]
},cv=5,return_train_score = False, n_iter = 8
)

In [60]:
cm3.fit(x,y)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=8,
                   param_distributions={'metric': ['euclidean', 'manhattan'],
                                        'n_neighbors': [3, 5, 7, 9, 11, 13, 15,
                                                        17, 19, 21, 25, 27,
                                                        31],
                                        'weights': ['uniform', 'distance']})

In [61]:
result = pd.DataFrame(cm3.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_weights,param_n_neighbors,param_metric,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003175,0.001235,0.003422,0.001416,distance,25,manhattan,"{'weights': 'distance', 'n_neighbors': 25, 'me...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,3
1,0.002301,0.000200,0.003483,0.000334,uniform,25,euclidean,"{'weights': 'uniform', 'n_neighbors': 25, 'met...",0.933333,0.966667,0.933333,0.966667,1.0,0.960000,0.024944,8
2,0.002526,0.000257,0.002857,0.000352,distance,27,euclidean,"{'weights': 'distance', 'n_neighbors': 27, 'me...",0.966667,0.966667,0.966667,0.966667,1.0,0.973333,0.013333,1
3,0.002184,0.000026,0.003229,0.000037,uniform,9,manhattan,"{'weights': 'uniform', 'n_neighbors': 9, 'metr...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,1
4,0.002136,0.000045,0.002524,0.000141,distance,9,manhattan,"{'weights': 'distance', 'n_neighbors': 9, 'met...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,6
5,0.002102,0.000025,0.003140,0.000022,uniform,19,euclidean,"{'weights': 'uniform', 'n_neighbors': 19, 'met...",0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,3
6,0.002134,0.000021,0.003179,0.000063,uniform,21,euclidean,"{'weights': 'uniform', 'n_neighbors': 21, 'met...",0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,3
7,0.002180,0.000039,0.002423,0.000027,distance,5,manhattan,"{'weights': 'distance', 'n_neighbors': 5, 'met...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,6