<a href="https://colab.research.google.com/github/MaheenZaheer/Machine-Learning/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
df = pd.read_csv("/content/final_dataset.csv")

In [22]:
df.head()

                                                text     emotion
0  i feel rather funny ending with so many dupes ...         fun
1                     i feel surprised by the result    surprise
2                    i am officially feeling festive     neutral
3  i suddenly found myself standing before this w...    surprise
4  i look at the meager pile of food i purchased ...  enthusiasm

In [23]:
df["emotion"].unique()

array(['fun', 'surprise', 'neutral', 'enthusiasm', 'happiness', 'hate',
       'sadness', 'empty', 'love', 'relief', 'anger'], dtype=object)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106355 entries, 0 to 106354
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   text     106355 non-null  object
 1   emotion  106355 non-null  object
dtypes: object(2)
memory usage: 1.6+ MB

In [25]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["emotion"] = le.fit_transform(df["emotion"])

In [26]:
df.head()

                                                text  emotion
0  i feel rather funny ending with so many dupes ...        3
1                     i feel surprised by the result       10
2                    i am officially feeling festive        7
3  i suddenly found myself standing before this w...       10
4  i look at the meager pile of food i purchased ...        2

In [27]:
df["text"] = df["text"].apply(lambda x :x.lower())

In [28]:
df

                                                     text  emotion
0       i feel rather funny ending with so many dupes ...        3
1                          i feel surprised by the result       10
2                         i am officially feeling festive        7
3       i suddenly found myself standing before this w...       10
4       i look at the meager pile of food i purchased ...        2
...                                                   ...      ...
106350  i used to feel strongly about how much i hated...        5
106351  i feel like i just got a spirit booster this r...       10
106352  i could come up with is that i was really feel...        0
106353  i find it really it helps to have an outfit of...        8
106354  i can t help feeling surprised by his sudden call       10

[106355 rows x 2 columns]

In [29]:
import string
def remove_punc(text):
  for punc in string.punctuation:
    text = text.replace(punc,"")
  return text

In [30]:
df["text"] = df["text"].apply(remove_punc)
df["text"]

0         i feel rather funny ending with so many dupes ...
1                            i feel surprised by the result
2                           i am officially feeling festive
3         i suddenly found myself standing before this w...
4         i look at the meager pile of food i purchased ...
                                ...
106350    i used to feel strongly about how much i hated...
106351    i feel like i just got a spirit booster this r...
106352    i could come up with is that i was really feel...
106353    i find it really it helps to have an outfit of...
106354    i can t help feeling surprised by his sudden call
Name: text, Length: 106355, dtype: object

In [31]:
def remove_num(text):
  for i in text:
    if i.isdigit():
      text = text.replace(i,"")
  return text

In [32]:
df["text"] = df["text"].apply(remove_num)
df["text"]
#we do not have emjois here but if we have then simply use isascii since ascii is for the txt and numbers but the unicode is for everything so we can use above for loop for that purpose

0         i feel rather funny ending with so many dupes ...
1                            i feel surprised by the result
2                           i am officially feeling festive
3         i suddenly found myself standing before this w...
4         i look at the meager pile of food i purchased ...
                                ...
106350    i used to feel strongly about how much i hated...
106351    i feel like i just got a spirit booster this r...
106352    i could come up with is that i was really feel...
106353    i find it really it helps to have an outfit of...
106354    i can t help feeling surprised by his sudden call
Name: text, Length: 106355, dtype: object

In [33]:
#remove stopword it is necessary in nlp but not in deep learning
from nltk.corpus import stopwords
import nltk
from nltk.corpus import stopwords

# Download the missing dataset
nltk.download('stopwords')

# Access the stopwords
stop_words = set(stopwords.words("english"))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data] Error downloading 'stopwords' from
[nltk_data]     <https://raw.githubusercontent.com/nltk/nltk_data/gh-
[nltk_data]     pages/packages/corpora/stopwords.zip>:   HTTP Error
[nltk_data]     503: first byte timeout

False

In [37]:

# def remove_stopwords(text):
#   word_tokens = word_tokenize(text)
#   filtered_text = [word for word in word_tokens if word not in stop_words]
#   return " ".join(filtered_text)

In [38]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    words = []

    for word in tokens:
        if word not in stop_words:
            words.append(word)

    return " ".join(words)

In [39]:
df["text"] = df["text"].apply(remove_stopwords)
df["text"]

0         feel rather funny ending many dupes always pre...
1                                     feel surprised result
2                                officially feeling festive
3         suddenly found standing woman dressed like pri...
4         look meager pile food purchased week feeling p...
                                ...
106350    used feel strongly much hated curly feel stron...
106351    feel like got spirit booster refers amazing ne...
106352    could come really feeling victimized made abso...
106353    find really helps outfit favourite basic piece...
106354                   help feeling surprised sudden call
Name: text, Length: 106355, dtype: object

In [40]:
# we have techniques for vectorization like bag of words one hot encoding (failed search it on google why ) tf-idf
# currently we gonna use bag of words it works on frequency for this first of all we goona convert our txt in vocab
# after thta from that vocab we calculate each word how many it is apperaed in sentaence or documnet samilarly we do this for all coupus

In [ ]:
#after completing this we will